Update kotlinx.serialization to v1.5.1 (#30)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[org.jetbrains.kotlinx:kotlinx-serialization-json](https://togithub.com/Kotlin/kotlinx.serialization)
| `1.4.1` -> `1.5.1` |
[![age](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlinx:kotlinx-serialization-json/1.5.1/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlinx:kotlinx-serialization-json/1.5.1/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlinx:kotlinx-serialization-json/1.5.1/compatibility-slim/1.4.1)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlinx:kotlinx-serialization-json/1.5.1/confidence-slim/1.4.1)](https://docs.renovatebot.com/merge-confidence/)
|
|
[org.jetbrains.kotlinx:kotlinx-serialization-core](https://togithub.com/Kotlin/kotlinx.serialization)
| `1.4.1` -> `1.5.1` |
[![age](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlinx:kotlinx-serialization-core/1.5.1/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlinx:kotlinx-serialization-core/1.5.1/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlinx:kotlinx-serialization-core/1.5.1/compatibility-slim/1.4.1)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlinx:kotlinx-serialization-core/1.5.1/confidence-slim/1.4.1)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>Kotlin/kotlinx.serialization</summary>

###
[`v1.5.1`](https://togithub.com/Kotlin/kotlinx.serialization/blob/HEAD/CHANGELOG.md#&#8203;151--2023-05-11)

\==================
This release contains an important Native targets overhaul, as well as
numerous enhancements and bugfixes.
Kotlin 1.8.21 is used by default.

##### New set of Native targets

The official [Kotlin target support
policy](https://kotlinlang.org/docs/native-target-support.html) has
recently been published
describing new target policy: each target belongs to a certain *tier*,
and different tiers have different stability guarantees.
The official recommendation for library authors is to support targets up
to Tier 3,
and kotlinx.serialization now follows it.
It means that in this release, there are a lot of new targets added from
this tier,
such as `androidNativeX86` or `watchosDeviceArm64`.
Note that since they belong to Tier 3, they're not auto-tested on CI.

kotlinx.serialization also ships some deprecated Kotlin/Native targets
that do not belong to any tier (e.g. `iosArm32`, `mingwX86`).
We'll continue to release them, but we do not provide support for them,
nor do we plan to add new targets from the deprecated list.

##### Improvements in Json elements

There are two new function sets that should make creating raw Json
elements easier.
[First one](https://togithub.com/Kotlin/kotlinx.serialization/pull/2160)
contains overloads for `JsonPrimitive` constructor-like function
that accept unsigned types: `JsonPrimitive(1u)`.
[Second
one](https://togithub.com/Kotlin/kotlinx.serialization/pull/2156) adds
new `addAll` functions to `JsonArrayBuilder` to be used with collections
of numbers, booleans or strings: `buildJsonArray { addAll(listOf(1, 2,
3)) }`
Both were contributed to us by [aSemy](https://togithub.com/aSemy).

##### Other enhancements

- **Potential source-breaking change**: Rename json-okio `target`
variables to `sink`
([#&#8203;2226](https://togithub.com/Kotlin/kotlinx.serialization/issues/2226))
- Function to retrieve KSerializer by KClass and type arguments
serializers
([#&#8203;2291](https://togithub.com/Kotlin/kotlinx.serialization/issues/2291))
- Added FormatLanguage annotation to Json methods
([#&#8203;2234](https://togithub.com/Kotlin/kotlinx.serialization/issues/2234))
- Properties Format: Support sealed/polymorphic classes as class
properties
([#&#8203;2255](https://togithub.com/Kotlin/kotlinx.serialization/issues/2255))

##### Bugfixes

- KeyValueSerializer: Fix missing call to endStructure()
([#&#8203;2272](https://togithub.com/Kotlin/kotlinx.serialization/issues/2272))
- ObjectSerializer: Respect sequential decoding
([#&#8203;2273](https://togithub.com/Kotlin/kotlinx.serialization/issues/2273))
- Fix value class encoding in various corner cases
([#&#8203;2242](https://togithub.com/Kotlin/kotlinx.serialization/issues/2242))
- Fix incorrect json decoding iterator's .hasNext() behavior on
array-wrapped inputs
([#&#8203;2268](https://togithub.com/Kotlin/kotlinx.serialization/issues/2268))
- Fix memory leak caused by invalid KTypeWrapper's equals method
([#&#8203;2274](https://togithub.com/Kotlin/kotlinx.serialization/issues/2274))
- Fixed NoSuchMethodError when parsing a JSON stream on Java 8
([#&#8203;2219](https://togithub.com/Kotlin/kotlinx.serialization/issues/2219))
- Fix MissingFieldException duplication
([#&#8203;2213](https://togithub.com/Kotlin/kotlinx.serialization/issues/2213))

###
[`v1.5.0`](https://togithub.com/Kotlin/kotlinx.serialization/blob/HEAD/CHANGELOG.md#&#8203;150--2023-02-27)

\==================

This release contains all features and bugfixes from 1.5.0-RC plus some
experimental features and bugfixes on its own (see below).
Kotlin 1.8.10 is used as a default.

##### HoconEncoder and HoconDecoder interfaces and HOCON-specific
serializers

These interfaces work in a way similar to `JsonEncoder` and
`JsonDecoder`: they allow intercepting (de)serialization process,
making writing if custom HOCON-specific serializers easier. New
`ConfigMemorySizeSerializer` and `JavaDurationSerializer` already make
use of them.
See more details in the
[PR](https://togithub.com/Kotlin/kotlinx.serialization/pull/2094).
Big thanks to [Alexander Mikhailov](https://togithub.com/alexmihailov)
for contributing this!

##### Ability to read buffered huge strings in custom Json deserializers

New interface `ChunkedDecoder` allows you to read huge strings that may
not fit in memory by chunks.
Currently, this interface is only implemented by Json decoder that works
with strings and streams,
but we may expand it later, if there's a demand for it.
See more details in the
[PR](https://togithub.com/Kotlin/kotlinx.serialization/pull/2012)
authored by [Alexey Sviridov](https://togithub.com/fred01).

##### Bugfixes

- Improve runtime exceptions messages
([#&#8203;2180](https://togithub.com/Kotlin/kotlinx.serialization/issues/2180))
- Added support for null values for nullable enums in lenient mode
([#&#8203;2176](https://togithub.com/Kotlin/kotlinx.serialization/issues/2176))
- Prevent class loaders from leaking when using ClassValue cache
([#&#8203;2175](https://togithub.com/Kotlin/kotlinx.serialization/issues/2175))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://app.renovatebot.com/dashboard#github/kyhule/polyworld-external-catalog).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNS4xMTAuMCIsInVwZGF0ZWRJblZlciI6IjM1LjExMC4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiJ9-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Kyle Lehman <kyhule@users.noreply.github.com>